services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=logs-db
    networks:
      - app-network

  log-keeper:
    build:
      context: .
      dockerfile: ./LogKeeperPg/Dockerfile
    container_name: log-keeper
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5171:5171"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=logs-db
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge